spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://172.20.10.9:3306/springboot?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
  jackson:
    default-property-inclusion: non_null
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
server:
  servlet:
    context-path: /sell
#logging:
#  file:
#    path: C:/myLogs
#  level:
 #     root: debug
 # pattern:
 #     console: "%d - %msg%n"




